export const main = 'MAIN';
export const ADD_CHILD = 'ADD_CHILD';
export const APPEND_CHILD = 'APPEND_CHILD';
export const ADD_SIBLING = 'ADD_SIBLING';
export const REMOVE_CELL = 'REMOVE_CELL';
export const APPEND_RIGHT_SIBLING = 'APPEND_RIGHT_SIBLING';
export const APPEND_LEFT_SIBLING = 'APPEND_LEFT_SIBLING';
export const TOGGLE_ESTIMATION = 'TOGGLE_ESTIMATION';
